#!/usr/bin/env python
import sys
import os

SCRIPTS_DIR = os.path.dirname(os.path.realpath(__file__))
REPO_DIR = os.path.dirname(SCRIPTS_DIR)

if os.path.isdir(os.path.join(REPO_DIR, "scripts")):
    # The file is not installed, so assume we are in the repo and that
    #   version should be used:
    sys.path.insert(0, REPO_DIR)

from blnk import main  # noqa: E402

if __name__ == "__main__":
    sys.exit(main())
